version: '3'
services:
    api:
        build:
          dockerfile: Dockerfile.dev
          context: ./server
        volumes:
          - /app/node_modules
          - ./server:/app
    nginx:
      restart: always
      build:
        dockerfile: Dockerfile.dev
        context: ./nginx
      ports:
        - '80:80'
      depends_on: 
        - api
        - client  
    client:
      build:
        dockerfile: Dockerfile.dev
        context: ./frontend
      volumes:
        - /app/node_modules
        - ./frontend:/app